# Generated by Django 4.2.7 on 2023-11-04 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mentorshiparticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiparticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshiparticle',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='mentorshiparticle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
