# Generated by Django 4.2.7 on 2023-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_category_tags_delete_mentorshiparticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blog/static/blogimages/'),
        ),
    ]
