# Generated by Django 4.2.7 on 2023-11-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('photo', models.ImageField(upload_to='dla_pictures')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.photo_tag')),
            ],
        ),
    ]
