# Generated by Django 4.2.7 on 2023-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_photo_tag_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='articleImages'),
        ),
    ]
